//
//  MVMessageRadioStatus.h
//  MAVLink communications protocol built from common.xml
//
//  Created by mavgen_objc.py
//  http://qgroundcontrol.org/mavlink
//

#import "MVMessage.h"

/*!
 Class that represents a RADIO_STATUS Mavlink message.

 @discussion Status generated by radio and injected into MAVLink stream.
 */
@interface MVMessageRadioStatus : MVMessage

- (id)initWithSystemId:(uint8_t)systemId componentId:(uint8_t)componentId rssi:(uint8_t)rssi remrssi:(uint8_t)remrssi txbuf:(uint8_t)txbuf noise:(uint8_t)noise remnoise:(uint8_t)remnoise rxerrors:(uint16_t)rxerrors fixed:(uint16_t)fixed;

//! Local (message sender) recieved signal strength indication in device-dependent units/scale. Values: [0-254], 255: invalid/unknown.
- (uint8_t)rssi;

//! Remote (message receiver) signal strength indication in device-dependent units/scale. Values: [0-254], 255: invalid/unknown.
- (uint8_t)remrssi;

//! Remaining free transmitter buffer space.
- (uint8_t)txbuf;

//! Local background noise level. These are device dependent RSSI values (scale as approx 2x dB on SiK radios). Values: [0-254], 255: invalid/unknown.
- (uint8_t)noise;

//! Remote background noise level. These are device dependent RSSI values (scale as approx 2x dB on SiK radios). Values: [0-254], 255: invalid/unknown.
- (uint8_t)remnoise;

//! Count of radio packet receive errors (since boot).
- (uint16_t)rxerrors;

//! Count of error corrected radio packets (since boot).
- (uint16_t)fixed;

@end
